### ISSUE TITLE
rotation can clip through already placed pieces

### ISSUE THREAD

**Issue by thomcc** [kirjavascript/blessed-tetris#4]
noticed this while playing. tgm-style wall kicking is easy to implement and probably worth doing - if you can't do the rotation immediately, try one space to the right, if that one still doesn't work, then try one space to the left, before giving up. there are a few [exceptions](http://tetris.wikia.com/wiki/TGM_rotation#Wall_kicks) but they don't really seem worth implementing to me.

**Comment by thomcc** [comment]
it looks like you do wall kicking already, so scratch that, you just need to handle the case where the kick pushes you out of one wall into another

**Comment by kirjavascript** [comment]
[I think this should fix it](https://github.com/kirjavascript/blessed-tetris/commit/650988ba97c93dcffd649382b047b1ac38540c4d)

is this correct?

**Comment by thomcc** [comment]
lgtm!
